### ISSUE TITLE
Hard Bug update 1.5 break company map

### ISSUE THREAD

**Issue by Xeraccoon** [ever39/LocalFlashlight#13]
Hello, I did tests to ensure that this was the case and since update 1.5 of the mod, the company map remains loading, the lever displays that the ship is moving and I never succeed at destination, in the logs there are errors between matty fixes and casino but it doesn't come from that, I don't understand how the update on local flash light could break the company, I post the logs even if I don't haven't seen any bugs regarding the display plugin inside
[local flash light.txt](https://github.com/user-attachments/files/17839964/local.flash.light.txt)

code of modpack : 01934d07-7681-dcb2-826d-8ee3ef23d8ae

**Comment by ever39** [comment]
fixed this, and i'll release the small hotfix update in a bit, turns out this was in fact gamebreaking as it would prevent anybody with the mod from going to company building (because the mod was checking for a nonexistent breaker box and as a result of not finding anything it would brick the entire level loading sequence), so thanks for the bug report! :)

**Comment by ever39** [comment]
now fixed in v1.5.1
